title:              Rahul Gujar
email:              rgujar@gmail.com
description:        Welcome to my Blog
author:             Rahul Gujar
baseurl:            ""
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   rahulgujar
linkedin_username:  rgujar

theme: jekyll-theme-clean-blog

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
